spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #??
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true # ?? system.out ?? ???
        dialect: org.hibernate.dialect.H2Dialect #??

logging:
  level:
    org.hibernate.sql: debug
